# Generated by Django 2.2.24 on 2023-10-26 11:31

from django.db import migrations


def set_new_builting(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gt=2014).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_builting),
    ]
