# Generated by Django 2.2.24 on 2023-10-26 22:39
import phonenumbers
import re
from django.db import migrations


def clean_phone_number(phone_number):
    # Remove non-numeric characters from the phone number
    cleaned_number = re.sub(r'\D', '', phone_number)
    return cleaned_number


def number_to_pure_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners_number = flat.owners_phonenumber
        cleaned_number = clean_phone_number(owners_number)
        if cleaned_number:
            # Attempt to parse the cleaned phone number
            parsed_owners_number = phonenumbers.parse(cleaned_number, "RU")
            if phonenumbers.is_possible_number(parsed_owners_number) and phonenumbers.is_valid_number(parsed_owners_number):
                flat.owner_pure_phone = parsed_owners_number
                flat.save()
            else:
                flat.owner_pure_phone = None
                flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231027_0127'),
    ]

    operations = [
        migrations.RunPython(number_to_pure_number),
    ]
