# Generated by Django 2.2.24 on 2023-10-26 23:56

from django.db import migrations


def move_users_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat_set = Flat.objects.all()
    flat_iterator = flat_set.iterator()
    try:
        first_flat = next(flat_iterator)
    except StopIteration:
        # No rows were found, so do nothing.
        pass
    else:
        # At least one row was found, so iterate over
        # all the rows, including the first one.
        from itertools import chain
        for flat in chain([first_flat], flat_iterator):
            owner = flat.owner
            owners_phonenumber = flat.owners_phonenumber
            owner_pure_phone = flat.owner_pure_phone
            Owner.objects.get_or_create(
                owner=owner, owners_phonenumber=owners_phonenumber,
                defaults={
                    'owner_pure_phone': owner_pure_phone,
                })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(move_users_to_owners),
    ]
