# Generated by Django 2.2.24 on 2023-10-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231028_1030'),
    ]

    operations = [
    ]
