# Generated by Django 2.2.24 on 2023-11-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20231101_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complainer',
            new_name='author',
        ),
    ]
